# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 096e8b5aca8f95817c64f907858eeb42e624028e21f81c6695c0d98bb9c50fe0772fa73a9ce54d629353813f10ea024353a0299324dd4c7070b12d718560b796

test:
  secret_key_base: d1795f213790c99919d594feeb2383daab6f7cfd336e126be887ea5974721ae18a459a9daaba4486cabbac11d60131b5ef04c781732b357d678866f939438b4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
